server:
  ssl:
    key-store-type: PKCS12
    key-store: extra/ks.p12
    key-store-password: abcabc
    key-alias: awh
    enabled: true
  port: 8443
logging:
  level:
    root: INFO
spring:
  devtools:
    add-properties: true
    livereload:
      enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
kubeomatic-io:
  timebomb:
    admission:
      review:
        apiversion: admission.k8s.io/v1
        kind: AdmissionReview
      response:
        patch-type: JSONPatch
    schedule:
      interval:
        seconds: JSONPatch
    timer:
      default: 1080
    label:
      timebomb: kubeomatic-io-timebomb
    annotation:
      valid: kubeomatic-io-timebomb-valid
      sku: kubeomatic-io-timebomb-sku
      description: kubeomatic-io-timebomb-description