---
apiVersion: v1
kind: Namespace
metadata:
  name: awh
  labels:
    admission-webhook: enabled
---
apiVersion: v1
kind: Secret
metadata:
  name: awh-secret
  namespace: awh
  annotations:
    kubernetes.io/service-account.name: awh
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awh
  namespace: awh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-delete-pods
  namespace: awh
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["pods"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awh-delete-pods
  namespace: awh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-delete-pods
  namespace: awh
subjects:
  - kind: ServiceAccount
    name: awh
    namespace: awh

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awh-reader
  namespace: awh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: awh
    namespace: awh

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awh
  namespace: awh
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: awh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: awh
    spec:
      serviceAccountName: awh
      containers:
        - image: TEMPLATE_DEPLOY_IMAGE
          name: awh
          env:
            - name: ENV_SERVICE_HOST
              value: "10.96.0.1"
            - name: ENV_SERVICE_PORT
              value: "443"
          ports:
            - containerPort: 8443
              name: awh-web-svc
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: awh-service
spec:
  selector:
    app.kubernetes.io/name: awh
  ports:
    - name: awh-port
      protocol: TCP
      port: 443
      targetPort: awh-web-svc
  type: ClusterIP
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "awh-service.awh.svc.cluster.local"
webhooks:
  - name: "awh-service.awh.svc.cluster.local"
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
#    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        br.com.clusterlab.timebomb: enabled
    rules:
      - apiGroups: ["*"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: awh
        name: awh-service
        path: /validate/pods
        port: 443
      caBundle: TEMPLATE_VALIDATINGWH_CAROOT