#apiVersion: v1
#kind: Pod
#metadata:
#  name: awh
#  labels:
#    app.kubernetes.io/name: awh
#spec:
#  containers:
#    - name: awh
#      image: TEMPLATE_IMAGE
#      ports:
#        - containerPort: 8443
#          name: awh-web-svc
#---
---
apiVersion: v1
kind: Namespace
metadata:
  name: awh
  labels:
    admission-webhook: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awh
  namespace: awh
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: awh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: awh
    spec:
      containers:
        - image: TEMPLATE_DEPLOY_IMAGE
          name: awh
          ports:
            - containerPort: 8443
              name: awh-web-svc
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: awh-service
spec:
  selector:
    app.kubernetes.io/name: awh
  ports:
    - name: awh-port
      protocol: TCP
      port: 443
      targetPort: awh-web-svc
  type: ClusterIP
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "awh-service.awh.svc.cluster.local"
webhooks:
  - name: "awh-service.awh.svc.cluster.local"
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
#    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: ["*"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: awh
        name: awh-service
        path: /validate/pods
        port: 443
      caBundle: TEMPLATE_VALIDATINGWH_CAROOT