---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    kubeomatic-io-timebomb: "enabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx
    kubeomatic-io-timebomb: "enabled"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        kubeomatic-io-timebomb: "enabled"
      annotations:
        kubeomatic-io-timebomb-timer: "1m"
        kubeomatic-io-timebomb-sku: "/avo/pai/filho"
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80