apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.common.name }}-clusterrolebinding
  # namespace: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.common.name }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.common.name }}-sa
    namespace: {{ .Release.Name }}