kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.common.name }}-schedule
data:
  application.properties: |-
    {{ (.Files.Get "properties/schedule.properties") | nindent 4 }}