kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.common.name }}-admission
data:
  application.properties: |-
    {{- .Values.admission.config | nindent 4}}
