apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}-admission
  namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.admission.spec.replicas }}
  selector:
    {{- with .Values.admission.selector.matchLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.common.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.common.name }}-sa
      containers:
        - image: "{{ .Values.common.registry }}/{{ .Values.common.repository }}/{{ .Values.common.image }}:admission-{{ .Values.schedule.imageTag | default .Values.common.imageTag }}"
          name: {{ .Values.common.name }}-admission
          volumeMounts:
            - name: app-properties
              mountPath: /app/resources
            - name: keystore
              mountPath: "/extra"
              readOnly: true
          ports:
            - containerPort: 8443
              name: admission-svc
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: app-properties
          configMap:
            name: {{ .Values.common.name }}-admission
        - name: keystore
          secret:
            secretName: {{ .Values.common.name }}-secret
            optional: false