apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "{{ .Values.common.name }}-admission-service.{{ .Release.Name }}.svc.cluster.local"
webhooks:
  - name: "{{ .Values.common.name }}-admission-service.{{ .Release.Name }}.svc.cluster.local"
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    #    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        kubeomatic-io-timebomb: "enabled"
    rules:
      - apiGroups: ["*"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["deployments"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Name }}
        name: {{ .Values.common.name }}-admission-service
        path: /api/mutation
        port: 443
      caBundle: {{ .Files.Get "tmp/rootCA.crt" | b64enc }}